###Get persons

GET http://localhost:9080/hotels/api/users

### Get person

GET http://localhost:9080/hotels/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4a

### Put user
// @no-cookie-jar
PUT http://localhost:9080/hotels/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4d
Content-Type: application/json

{
  "email": "test",
  "firstName": "Ludwik",
  "lastName": "asd",
  "password": "asddd"
}


### Get non person

GET http://localhost:9080/hotels/api/users/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0

### Get a person photo

GET http://localhost:9080/hotels/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/photo

### Get a non person photo

GET http://localhost:9080/hotels/api/users/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0/photo


### Create a user avatar

PUT http://localhost:9080/hotels/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/photo
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="sigrid.png'

< /home/student/188782/eloise.png

--boundary--

### Delete avatar

DELETE http://localhost:9080/hotels/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/photo

### Delete non user avatar

DELETE http://localhost:9080/hotels/api/users/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0/photo

### Update a user avatar

PATCH http://localhost:9080/hotels/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/photo
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="sigrid.png'

< /home/student/188782/calvian.png

--boundary--

### Get hotels

GET http://localhost:9080/hotels/api/hotels
Authorization: Basic YWRtaW5Ac2ltcGxlcnBnLmV4YW1wbGUuY29tOmFkbWluYWRtaW4=

### Get non hotel

GET http://localhost:9080/hotels/api/hotels/42d32cd8-08c7-46f4-ad80-034c1c83faea
Authorization: Basic YWRtaW5Ac2ltcGxlcnBnLmV4YW1wbGUuY29tOmFkbWluYWRtaW4=

### Get non hotel reservations

GET http://localhost:9080/hotels/api/hotels/42d32cd8-08c7-46f4-ad80-034c1c83faea/reservations

### Put hotel

// @no-cookie-jar
PUT http://localhost:9080/hotels/api/hotels/42d32cd8-08c7-46f4-ad80-034c1c83faea
Authorization: Basic YWRtaW5Ac2ltcGxlcnBnLmV4YW1wbGUuY29tOmFkbWluYWRtaW4=
Content-Type: application/json

{
  "name": "Radison",
  "city": "Gdansk",
  "rooms": 1
}

### Update hotel

PATCH http://localhost:9080/hotels/api/hotels/42d32cd8-08c7-46f4-ad80-034c1c83faea
Content-Type: application/json

{
  "name": "Radisson",
  "rooms": 2
}

### Delete hotel

// @no-cookie-jar
DELETE http://localhost:9080/hotels/api/hotels/42d32cd8-08c7-46f4-ad80-034c1c83faea
Authorization: Basic YWRtaW5Ac2ltcGxlcnBnLmV4YW1wbGUuY29tOmFkbWluYWRtaW4=


### Get reservations
// @no-cookie-jar
GET http://localhost:9080/hotels/api/reservations
#Authorization: Basic YWRtaW5Ac2ltcGxlcnBnLmV4YW1wbGUuY29tOmFkbWluYWRtaW4=
Authorization: Basic a2V2aW5AZXhhbXBsZS5jb206YWRtaW5hZG1pbg==

### Get non reservation

GET http://localhost:9080/hotels/api/reservations/663313ff-a5b7-463d-88bf-fe64c7a7f00d

### Put reservation
// @no-cookie-jar
PUT http://localhost:9080/hotels/api/hotels/42d32cd8-08c7-46f4-ad80-034c1c83faea/reservations/663313ff-a5b7-463d-88bf-fe64c7a7f00e
Authorization: Basic YWRtaW5Ac2ltcGxlcnBnLmV4YW1wbGUuY29tOmFkbWluYWRtaW4=
#Authorization: Basic a2V2aW5AZXhhbXBsZS5jb206YWRtaW5hZG1pbg==
Content-Type: application/json

{
  "startTime": "2024-05-02",
  "endTime": null,
  "status": "RESERVED"
}

### Update reservation

PATCH http://localhost:9080/hotels/api/reservations/663313ff-a5b7-463d-88bf-fe64c7a7f00d
Content-Type: application/json

{
  "endTime": "2024-06-01",
  "status": "CANCELLED"
}

### Delete reservation
// @no-cookie-jar
DELETE http://localhost:9080/hotels/api/reservations/663313ff-a5b7-463d-88bf-fe64c7a7f00e
Authorization: Basic YWRtaW5Ac2ltcGxlcnBnLmV4YW1wbGUuY29tOmFkbWluYWRtaW4=
#Authorization: Basic a2V2aW5AZXhhbXBsZS5jb206YWRtaW5hZG1pbg==
